# Generated by Django 2.2.7 on 2020-04-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['admission_number', 'department']},
        ),
    ]
