# Generated by Django 2.2.7 on 2020-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200418_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('uncle', 'uncle')], default='Father', max_length=100),
        ),
    ]
