# Generated by Django 2.2.7 on 2020-04-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_guardian_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_join',
            field=models.DateTimeField(default='1998-01-01'),
        ),
    ]
