# Generated by Django 2.2.7 on 2020-06-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200522_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='data_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_join',
            field=models.DateField(default='1998-01-01'),
        ),
    ]
