# Generated by Django 2.2.7 on 2020-04-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcNumber', models.IntegerField()),
                ('tcYear', models.IntegerField()),
                ('reasonforLeaving', models.CharField(choices=[('Course discontinued', 'Course discontinued'), ('Got Another Allotment', 'Got Another Allotment'), ('Course Completed', 'Course Completed')], max_length=50)),
                ('dateofApplication', models.DateField(auto_now=True)),
                ('promotionDate', models.DateField(auto_now=True)),
                ('lastclass', models.IntegerField(default=6)),
                ('promotedtoHigherClass', models.CharField(choices=[('Yes', 'yes'), ('No', 'No'), ('Result Not Announced', 'Result Not announced')], default='Result Not Announced', max_length=30)),
                ('proceedingInstitution', models.CharField(default='Result Not Announced', max_length=100)),
                ('lastAttendedDate', models.DateField(auto_now=True)),
                ('totalWorkingDay', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TcIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcNumber', models.IntegerField()),
                ('tcYear', models.IntegerField()),
                ('dateofIssue', models.DateField(auto_now=True)),
                ('conduct', models.CharField(default='Good', max_length=20)),
                ('tcApplication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tc.TcApplication')),
            ],
        ),
    ]
