# Generated by Django 2.2.7 on 2020-04-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcapplication',
            old_name='tc_appliaction_Number',
            new_name='tc_application_Number',
        ),
    ]
