# Generated by Django 2.2.7 on 2020-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0002_auto_20200418_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='duesCleared',
            field=models.BooleanField(default=True),
        ),
    ]
