# Generated by Django 2.2.7 on 2020-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0003_tcapplication_duescleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='fee_concession',
            field=models.BooleanField(default=True),
        ),
    ]
