# Generated by Django 2.2.7 on 2020-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0004_tcapplication_fee_concession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='dateofremovedfromrolls',
            field=models.DateField(auto_now=True),
        ),
    ]
