# Generated by Django 2.2.7 on 2020-06-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0006_auto_20200607_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='tc_issued',
            field=models.BooleanField(default=False),
        ),
    ]
